# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 04:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='邮箱')),
                ('name', models.CharField(max_length=20, verbose_name='联系人')),
                ('telephone', models.CharField(max_length=15, verbose_name='办公电话')),
                ('mobile', models.CharField(blank=True, max_length=11, verbose_name='手机')),
                ('fax', models.CharField(blank=True, max_length=15, verbose_name='传真')),
                ('skype', models.CharField(blank=True, max_length=15, verbose_name='skype')),
                ('QQ', models.CharField(blank=True, max_length=10, verbose_name='QQ')),
                ('company_name', models.CharField(max_length=80, verbose_name='公司名称')),
                ('company_abbr', models.CharField(max_length=20, verbose_name='公司简称')),
                ('company_address', models.CharField(blank=True, max_length=100, verbose_name='公司地址')),
                ('web_site', models.CharField(blank=True, max_length=50, verbose_name='公司网址')),
                ('company_about', models.TextField(blank=True, max_length=256, verbose_name='公司简介')),
                ('port_code', models.CharField(max_length=200, verbose_name='港口代码')),
                ('port_cname', models.CharField(max_length=200, verbose_name='港口名称')),
                ('country', models.CharField(max_length=30, verbose_name='国家')),
            ],
        ),
        migrations.CreateModel(
            name='bagType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50, verbose_name='中文名')),
                ('ename', models.CharField(blank=True, max_length=50, verbose_name='英文名')),
                ('ename_abbr', models.CharField(blank=True, max_length=20, verbose_name='英文简称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_name', models.CharField(max_length=100, verbose_name='货物名称')),
                ('cargo_type', models.CharField(max_length=2, verbose_name='货物类型')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='货量')),
                ('quantity_unit', models.CharField(choices=[('1', '吨'), ('2', '立方米')], max_length=1, verbose_name='货量单位')),
                ('laycan_start', models.DateField(verbose_name='受载期开始')),
                ('laycan_end', models.DateField(verbose_name='受载期结束')),
                ('package', models.CharField(blank=True, max_length=2, verbose_name='包装类型')),
                ('sf', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='积载因素')),
                ('ldRate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='装卸率')),
                ('frt_dollar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='运费(美元)')),
                ('frt_RMB', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='运费(人民币)')),
                ('crane', models.CharField(blank=True, max_length=100, verbose_name='吊具')),
                ('comm', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='佣金(%)')),
                ('term', models.CharField(blank=True, max_length=5, verbose_name='条款')),
                ('memo', models.TextField(blank=True, max_length=256, verbose_name='备注')),
                ('send_time', models.DateTimeField(verbose_name='发送时间')),
                ('record_time', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
            ],
        ),
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50, verbose_name='中文名')),
                ('ename', models.CharField(blank=True, max_length=50, verbose_name='英文名')),
                ('ename_abbr', models.CharField(blank=True, max_length=20, verbose_name='英文简称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='姓名')),
                ('post', models.CharField(blank=True, max_length=20, verbose_name='职位')),
                ('telephone', models.CharField(max_length=15, verbose_name='办公电话')),
                ('mobile', models.CharField(blank=True, max_length=15, verbose_name='手机')),
                ('fax', models.CharField(blank=True, max_length=15, verbose_name='传真')),
                ('skype', models.CharField(blank=True, max_length=15, verbose_name='skype')),
                ('qq', models.CharField(blank=True, max_length=10, verbose_name='QQ')),
                ('company_name', models.CharField(blank=True, max_length=80, verbose_name='公司名称')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], max_length=10, verbose_name='验证码类型')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('port_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='港口代码')),
                ('port_cname', models.CharField(max_length=30, verbose_name='港口中文名称')),
                ('port_ename', models.CharField(max_length=50, verbose_name='港口英文名称')),
                ('country', models.CharField(max_length=30, verbose_name='国家')),
                ('currency', models.CharField(max_length=10, verbose_name='货币')),
                ('time_zone', models.CharField(choices=[('0', 'UTC'), ('+1', 'UTC+1'), ('+2', 'UTC+2'), ('+3', 'UTC+3'), ('+4', 'UTC+4'), ('+5', 'UTC+5'), ('+6', 'UTC+6'), ('+7', 'UTC+7'), ('+8', 'UTC+8'), ('+9', 'UTC+9'), ('+10', 'UTC+10'), ('+11', 'UTC+11'), ('12', 'UTC12'), ('-11', 'UTC-11'), ('-10', 'UTC-10'), ('-9', 'UTC-9'), ('-8', 'UTC-8'), ('-7', 'UTC-7'), ('-6', 'UTC-6'), ('-5', 'UTC-5'), ('-4', 'UTC-4'), ('-3', 'UTC-3'), ('-2', 'UTC-2'), ('-1', 'UTC-1')], max_length=3, verbose_name='时区')),
                ('berth', models.CharField(blank=True, max_length=256, verbose_name='泊位')),
                ('max_loa', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='最大船长(米)')),
                ('draft_limit', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='吃水限制(米)')),
                ('lifts_tons', models.CharField(blank=True, max_length=50, null=True, verbose_name='装卸能力')),
                ('ldRate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='装卸率')),
                ('cranes_mobile', models.BooleanField(verbose_name='岸吊')),
                ('cranes_floating', models.BooleanField(verbose_name='浮吊')),
                ('web_site', models.CharField(blank=True, max_length=50, verbose_name='网站')),
                ('memo', models.TextField(blank=True, max_length=256, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='用户名')),
                ('record_id', models.IntegerField(verbose_name='记录编号')),
                ('selected_Time', models.DateTimeField(auto_now_add=True, verbose_name='筛选时间')),
                ('status', models.CharField(max_length=1, verbose_name='记录状态')),
                ('memo', models.TextField(blank=True, max_length=256)),
                ('selected_table', models.CharField(default='Cargo', editable=False, max_length=10, verbose_name='筛选记录类型')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SelectedTct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='用户名')),
                ('record_id', models.IntegerField(verbose_name='记录编号')),
                ('selected_Time', models.DateTimeField(auto_now_add=True, verbose_name='筛选时间')),
                ('status', models.CharField(max_length=1, verbose_name='记录状态')),
                ('memo', models.TextField(blank=True, max_length=256)),
                ('selected_table', models.CharField(default='Tct', editable=False, max_length=10, verbose_name='筛选记录类型')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SelectedTonnage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='用户名')),
                ('record_id', models.IntegerField(verbose_name='记录编号')),
                ('selected_Time', models.DateTimeField(auto_now_add=True, verbose_name='筛选时间')),
                ('status', models.CharField(max_length=1, verbose_name='记录状态')),
                ('memo', models.TextField(blank=True, max_length=256)),
                ('selected_table', models.CharField(default='Tonnage', editable=False, max_length=10, verbose_name='筛选记录类型')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='邮箱')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('post', models.CharField(blank=True, max_length=20, verbose_name='职位')),
                ('telephone', models.CharField(max_length=15, verbose_name='办公电话')),
                ('mobile', models.CharField(blank=True, max_length=15, verbose_name='手机')),
                ('fax', models.CharField(blank=True, max_length=15, verbose_name='传真')),
                ('skype', models.CharField(blank=True, max_length=15, verbose_name='skype')),
                ('qq', models.CharField(blank=True, max_length=10, verbose_name='QQ')),
                ('company_name', models.CharField(blank=True, max_length=80, verbose_name='公司名称')),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=20, verbose_name='船名')),
                ('dwt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='载重吨')),
                ('built', models.DateField(verbose_name='建造日期')),
                ('type', models.CharField(choices=[('1', '杂货船'), ('2', '散装船'), ('3', '多用途船'), ('4', '重吊船'), ('5', '集装箱船'), ('6', '汽船'), ('7', '液化气船'), ('8', '滚装船'), ('9', '化学品船')], max_length=2, verbose_name='船型')),
                ('flag', models.CharField(blank=True, max_length=20, verbose_name='船旗')),
                ('loa', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='船长(米)')),
                ('beam', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='船宽(米)')),
                ('depth', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='船深(米)')),
                ('draft', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='吃水(米)')),
                ('grain', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='舱容(立方米)')),
                ('hatch', models.IntegerField(verbose_name='舱数')),
                ('tpc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='每厘米吃水')),
                ('imo', models.CharField(blank=True, max_length=20, verbose_name='IMO No.')),
                ('call_sign', models.CharField(blank=True, max_length=20, verbose_name='呼号')),
                ('pi_club', models.CharField(blank=True, max_length=10, verbose_name='船东保赔协会')),
                ('ship_class', models.CharField(blank=True, max_length=10, verbose_name='船级')),
                ('gear', models.CharField(blank=True, max_length=20, verbose_name='船吊')),
                ('memo', models.TextField(blank=True, max_length=256, verbose_name='备注')),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50, verbose_name='中文名')),
                ('ename', models.CharField(blank=True, max_length=50, verbose_name='英文名')),
                ('ename_abbr', models.CharField(blank=True, max_length=20, verbose_name='英文简称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StarCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='用户名')),
                ('record_id', models.IntegerField(verbose_name='记录编号')),
                ('flag_Time', models.DateTimeField(auto_now_add=True, verbose_name='标记时间')),
                ('memo', models.TextField(blank=True, max_length=256, verbose_name='备注')),
                ('star_table', models.CharField(default='Cargo', editable=False, max_length=10, verbose_name='星标记录类型')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StarTct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='用户名')),
                ('record_id', models.IntegerField(verbose_name='记录编号')),
                ('flag_Time', models.DateTimeField(auto_now_add=True, verbose_name='标记时间')),
                ('memo', models.TextField(blank=True, max_length=256, verbose_name='备注')),
                ('star_table', models.CharField(default='Tct', editable=False, max_length=10, verbose_name='星标记录类型')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StarTonnage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='用户名')),
                ('record_id', models.IntegerField(verbose_name='记录编号')),
                ('flag_Time', models.DateTimeField(auto_now_add=True, verbose_name='标记时间')),
                ('memo', models.TextField(blank=True, max_length=256, verbose_name='备注')),
                ('star_table', models.CharField(default='Tonnage', editable=False, max_length=10, verbose_name='星标记录类型')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, max_length=50, verbose_name='租家')),
                ('dwt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='载重吨')),
                ('delivery', models.CharField(max_length=50, verbose_name='交付地点')),
                ('redelivery', models.CharField(max_length=50, verbose_name='交还地点')),
                ('laycan_start', models.DateField(verbose_name='受载期开始')),
                ('laycan_end', models.DateField(verbose_name='受载期结束')),
                ('duration', models.CharField(max_length=20, verbose_name='租期')),
                ('type', models.CharField(choices=[('1', '杂货船'), ('2', '散装船'), ('3', '多用途船'), ('4', '重吊船'), ('5', '集装箱船'), ('6', '汽船'), ('7', '液化气船'), ('8', '滚装船'), ('9', '化学品船')], max_length=2, verbose_name='船型')),
                ('max_age', models.IntegerField(blank=True, null=True, verbose_name='船龄限制(年)')),
                ('crane', models.CharField(blank=True, max_length=50, verbose_name='装卸能力')),
                ('grain', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='舱容(立方米)')),
                ('hatch', models.IntegerField(blank=True, null=True, verbose_name='舱数')),
                ('memo', models.TextField(blank=True, max_length=256, verbose_name='备注')),
                ('sendTime', models.DateTimeField(verbose_name='发送时间')),
                ('recordTime', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailmanage.CustomUser', verbose_name='记录人')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailmanage.Sender', verbose_name='发件人')),
            ],
        ),
        migrations.CreateModel(
            name='TermType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50, verbose_name='中文名')),
                ('ename', models.CharField(blank=True, max_length=50, verbose_name='英文名')),
                ('ename_abbr', models.CharField(blank=True, max_length=20, verbose_name='英文简称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tonnage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_start_date', models.DateField(verbose_name='空船开始日期')),
                ('open_end_date', models.DateField(verbose_name='空船结束日期')),
                ('open_area', models.CharField(max_length=50, verbose_name='空船区域')),
                ('memo', models.TextField(blank=True, max_length=256, verbose_name='备注')),
                ('send_time', models.DateTimeField(verbose_name='发送时间')),
                ('record_time', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailmanage.CustomUser', verbose_name='记录人')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailmanage.Sender', verbose_name='发件人')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailmanage.Ship', verbose_name='船舶')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='startonnage',
            unique_together=set([('user_name', 'record_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='startct',
            unique_together=set([('user_name', 'record_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='starcargo',
            unique_together=set([('user_name', 'record_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='selectedtonnage',
            unique_together=set([('user_name', 'record_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='selectedtct',
            unique_together=set([('user_name', 'record_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='selectedcargo',
            unique_together=set([('user_name', 'record_id')]),
        ),
        migrations.AddField(
            model_name='cargo',
            name='discharge_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge', to='emailmanage.Ship', verbose_name='卸货港'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='loading_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading', to='emailmanage.Ship', verbose_name='装货港'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='recorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailmanage.CustomUser', verbose_name='记录人'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailmanage.Sender', verbose_name='发件人'),
        ),
    ]
