# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 07:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20, verbose_name='中文名称')),
                ('ename', models.CharField(max_length=20, verbose_name='英文名称')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr_cname', models.CharField(max_length=20, verbose_name='中文简称')),
                ('full_cname', models.CharField(max_length=20, verbose_name='中文全称')),
                ('abbr_ename', models.CharField(max_length=20, verbose_name='英文简称')),
                ('full_ename', models.CharField(max_length=20, verbose_name='英文全称')),
                ('number_code', models.CharField(max_length=3, verbose_name='数字代码')),
                ('english_code_3', models.CharField(max_length=3, verbose_name='英文3码')),
                ('english_code_2', models.CharField(max_length=2, verbose_name='英文2码')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailmanage.Area', verbose_name='区域')),
            ],
        ),
        migrations.DeleteModel(
            name='EmailVerifyRecord',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='frt_RMB',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='frt_dollar',
        ),
        migrations.AddField(
            model_name='cargo',
            name='currency_unit',
            field=models.CharField(choices=[('1', '美元'), ('2', '人民币')], default=1, max_length=1, verbose_name='货币单位'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargo',
            name='frt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='运费'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cargo_type',
            field=models.CharField(max_length=20, verbose_name='货物类型'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='discharge_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge', to='emailmanage.Port', verbose_name='卸货港'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='loading_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading', to='emailmanage.Port', verbose_name='装货港'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='recorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录人'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='term',
            field=models.CharField(blank=True, choices=[('FLT', 'FLT-班轮条款'), ('FIOST', 'FIOST-船东不负责装、卸、堆装、平舱'), ('FI', 'FI-船东不负责装'), ('FO', 'FO-船东不负责卸'), ('FIO', 'FIO-船东不负责装、卸'), ('FILO', 'FILO-船东不负责装但负责卸'), ('LIFO', 'LIFO-船东负责装不负责卸')], max_length=5, verbose_name='条款'),
        ),
        migrations.AlterField(
            model_name='port',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailmanage.Country', verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='tct',
            name='recorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录人'),
        ),
        migrations.AlterField(
            model_name='tonnage',
            name='recorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录人'),
        ),
        migrations.AddField(
            model_name='port',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emailmanage.Area', verbose_name='区域'),
            preserve_default=False,
        ),
    ]
